const mockData = [
    {
      "ID": "f69f2983-9ef6-476a-9261-8b58b9adaf19af5",
      "Name": "Laptop Lenovo IdeaPad Gaming 3 15ACH6 15\t6 \" AMD Ryzen 5 16 GB / 512 GB czarny",
      "Model": "IdeaPad Gaming 3 15ACH6",
      "Typ": "standardowy",
      "Kod producenta": "82K200QYPB",
      "Przekątna ekranu": "15\t6 ",
      "Rozdzielczość (px)": "1920 x 1080",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "60 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 5",
      "Model procesora": "AMD Ryzen 5 5600H",
      "Liczba rdzeni procesora": 6,
      "Taktowanie bazowe procesora": "3\t3 GHz",
      "Wielkość pamięci RAM": "16 GB",
      "Maksymalna wielkość pamięci RAM": "16 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": 2,
      "Liczba wolnych slotów RAM": 1,
      "Pojemność dysku": "512 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce GTX 1650",
      "Pamięć karty graficznej": "4 GB",
      "Pojemność akumulatora (Wh)": "45 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "5 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.0\t USB 3.0 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "czarny",
      "Materiał": "tworzywo sztuczne",
      "Szerokość produktu": "35 cm",
      "Wysokość produktu": "2\t4 cm",
      "Głębokość produktu": "24 cm",
      "Waga produktu": "2\t25 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/11488b/02eb1e854502a213ab6180ba933f"
    },
    {
      "ID": "0d86a28a-19c1-4de3-b9d3-ccc6b94a5ee8",
      "Name": "Laptop Lenovo Legion 5 Pro 16ACH6H 16 \" AMD Ryzen 7 32 GB / 1024 GB szary",
      "Model": "Legion 5 Pro 16ACH6H",
      "Typ": "standardowy",
      "Kod producenta": "82JQ00G1GE",
      "Przekątna ekranu": 16,
      "Rozdzielczość (px)": "2560 x 1600",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "165 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 7",
      "Model procesora": "AMD Ryzen 7 5800H",
      "Liczba rdzeni procesora": 8,
      "Taktowanie bazowe procesora": "3\t2 GHz",
      "Wielkość pamięci RAM": "32 GB",
      "Maksymalna wielkość pamięci RAM": "32 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": "brak danych",
      "Liczba wolnych slotów RAM": "brak danych",
      "Pojemność dysku": "1024 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce RTX 3070",
      "Pamięć karty graficznej": "8 GB",
      "Pojemność akumulatora (Wh)": "80 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "4\t2 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t inne\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.1 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "szary",
      "Materiał": "metal",
      "Szerokość produktu": "35\t6 cm",
      "Wysokość produktu": "2\t1 cm",
      "Głębokość produktu": "26\t04 cm",
      "Waga produktu": "2\t45 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/119fbd/5b894d0e44aaac0a48fad9de5cac"
    },
    {
      "ID": "f69f2983-9ef6-476a-9261-8b58b9f1119af5",
      "Name": "Laptop Lenovo IdeaPad Gaming 3 15ACH6 15\t6 \" AMD Ryzen 5 16 GB / 512 GB czarny",
      "Model": "IdeaPad Gaming 3 15ACH6",
      "Typ": "standardowy",
      "Kod producenta": "82K200QYPB",
      "Przekątna ekranu": "15\t6 ",
      "Rozdzielczość (px)": "1920 x 1080",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "60 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 5",
      "Model procesora": "AMD Ryzen 5 5600H",
      "Liczba rdzeni procesora": 6,
      "Taktowanie bazowe procesora": "3\t3 GHz",
      "Wielkość pamięci RAM": "16 GB",
      "Maksymalna wielkość pamięci RAM": "16 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": 2,
      "Liczba wolnych slotów RAM": 1,
      "Pojemność dysku": "512 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce GTX 1650",
      "Pamięć karty graficznej": "4 GB",
      "Pojemność akumulatora (Wh)": "45 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "5 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.0\t USB 3.0 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "czarny",
      "Materiał": "tworzywo sztuczne",
      "Szerokość produktu": "35 cm",
      "Wysokość produktu": "2\t4 cm",
      "Głębokość produktu": "24 cm",
      "Waga produktu": "2\t25 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/11488b/02eb1e854502a213ab6180ba933f"
    },
    {
      "ID": "0d86a28a-19c1-4de3-b9d3-3213ccc6b94a5ee8",
      "Name": "Laptop Lenovo Legion 5 Pro 16ACH6H 16 \" AMD Ryzen 7 32 GB / 1024 GB szary",
      "Model": "Legion 5 Pro 16ACH6H",
      "Typ": "standardowy",
      "Kod producenta": "82JQ00G1GE",
      "Przekątna ekranu": 16,
      "Rozdzielczość (px)": "2560 x 1600",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "165 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 7",
      "Model procesora": "AMD Ryzen 7 5800H",
      "Liczba rdzeni procesora": 8,
      "Taktowanie bazowe procesora": "3\t2 GHz",
      "Wielkość pamięci RAM": "32 GB",
      "Maksymalna wielkość pamięci RAM": "32 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": "brak danych",
      "Liczba wolnych slotów RAM": "brak danych",
      "Pojemność dysku": "1024 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce RTX 3070",
      "Pamięć karty graficznej": "8 GB",
      "Pojemność akumulatora (Wh)": "80 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "4\t2 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t inne\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.1 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "szary",
      "Materiał": "metal",
      "Szerokość produktu": "35\t6 cm",
      "Wysokość produktu": "2\t1 cm",
      "Głębokość produktu": "26\t04 cm",
      "Waga produktu": "2\t45 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/119fbd/5b894d0e44aaac0a48fad9de5cac"
    },
    {
      "ID": "f69f2983-9ef6-476a-9261-8b58b9aaaaaaaf19af5",
      "Name": "Laptop Lenovo IdeaPad Gaming 3 15ACH6 15\t6 \" AMD Ryzen 5 16 GB / 512 GB czarny",
      "Model": "IdeaPad Gaming 3 15ACH6",
      "Typ": "standardowy",
      "Kod producenta": "82K200QYPB",
      "Przekątna ekranu": "15\t6 ",
      "Rozdzielczość (px)": "1920 x 1080",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "60 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 5",
      "Model procesora": "AMD Ryzen 5 5600H",
      "Liczba rdzeni procesora": 6,
      "Taktowanie bazowe procesora": "3\t3 GHz",
      "Wielkość pamięci RAM": "16 GB",
      "Maksymalna wielkość pamięci RAM": "16 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": 2,
      "Liczba wolnych slotów RAM": 1,
      "Pojemność dysku": "512 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce GTX 1650",
      "Pamięć karty graficznej": "4 GB",
      "Pojemność akumulatora (Wh)": "45 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "5 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.0\t USB 3.0 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "czarny",
      "Materiał": "tworzywo sztuczne",
      "Szerokość produktu": "35 cm",
      "Wysokość produktu": "2\t4 cm",
      "Głębokość produktu": "24 cm",
      "Waga produktu": "2\t25 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/11488b/02eb1e854502a213ab6180ba933f"
    },
    {
      "ID": "0d86a28a-19c1-4de3-b9d3-ccc6b94a5ee8564",
      "Name": "Laptop Lenovo Legion 5 Pro 16ACH6H 16 \" AMD Ryzen 7 32 GB / 1024 GB szary",
      "Model": "Legion 5 Pro 16ACH6H",
      "Typ": "standardowy",
      "Kod producenta": "82JQ00G1GE",
      "Przekątna ekranu": 16,
      "Rozdzielczość (px)": "2560 x 1600",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "165 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 7",
      "Model procesora": "AMD Ryzen 7 5800H",
      "Liczba rdzeni procesora": 8,
      "Taktowanie bazowe procesora": "3\t2 GHz",
      "Wielkość pamięci RAM": "32 GB",
      "Maksymalna wielkość pamięci RAM": "32 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": "brak danych",
      "Liczba wolnych slotów RAM": "brak danych",
      "Pojemność dysku": "1024 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce RTX 3070",
      "Pamięć karty graficznej": "8 GB",
      "Pojemność akumulatora (Wh)": "80 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "4\t2 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t inne\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.1 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "szary",
      "Materiał": "metal",
      "Szerokość produktu": "35\t6 cm",
      "Wysokość produktu": "2\t1 cm",
      "Głębokość produktu": "26\t04 cm",
      "Waga produktu": "2\t45 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/119fbd/5b894d0e44aaac0a48fad9de5cac"
    },
    {
      "ID": "f69f2--983-9ef6-476a-9261-8b58b9f19af5",
      "Name": "Laptop Lenovo IdeaPad Gaming 3 15ACH6 15\t6 \" AMD Ryzen 5 16 GB / 512 GB czarny",
      "Model": "IdeaPad Gaming 3 15ACH6",
      "Typ": "standardowy",
      "Kod producenta": "82K200QYPB",
      "Przekątna ekranu": "15\t6 ",
      "Rozdzielczość (px)": "1920 x 1080",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "60 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 5",
      "Model procesora": "AMD Ryzen 5 5600H",
      "Liczba rdzeni procesora": 6,
      "Taktowanie bazowe procesora": "3\t3 GHz",
      "Wielkość pamięci RAM": "16 GB",
      "Maksymalna wielkość pamięci RAM": "16 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": 2,
      "Liczba wolnych slotów RAM": 1,
      "Pojemność dysku": "512 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce GTX 1650",
      "Pamięć karty graficznej": "4 GB",
      "Pojemność akumulatora (Wh)": "45 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "5 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.0\t USB 3.0 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "czarny",
      "Materiał": "tworzywo sztuczne",
      "Szerokość produktu": "35 cm",
      "Wysokość produktu": "2\t4 cm",
      "Głębokość produktu": "24 cm",
      "Waga produktu": "2\t25 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/11488b/02eb1e854502a213ab6180ba933f"
    },
    {
      "ID": "0dasd86a28a-19c1-4de3-b9d3-ccc6b94a5ee8",
      "Name": "Laptop Lenovo Legion 5 Pro 16ACH6H 16 \" AMD Ryzen 7 32 GB / 1024 GB szary",
      "Model": "Legion 5 Pro 16ACH6H",
      "Typ": "standardowy",
      "Kod producenta": "82JQ00G1GE",
      "Przekątna ekranu": 16,
      "Rozdzielczość (px)": "2560 x 1600",
      "Powłoka matrycy": "matowa",
      "Typ matrycy": "IPS",
      "Odświeżanie matrycy": "165 Hz",
      "Ekran dotykowy": "nie",
      "Seria procesora": "AMD Ryzen 7",
      "Model procesora": "AMD Ryzen 7 5800H",
      "Liczba rdzeni procesora": 8,
      "Taktowanie bazowe procesora": "3\t2 GHz",
      "Wielkość pamięci RAM": "32 GB",
      "Maksymalna wielkość pamięci RAM": "32 GB",
      "Typ pamięci RAM": "DDR4",
      "Częstotliwość taktowania pamięci (MHz)": 3200,
      "Liczba slotów RAM": "brak danych",
      "Liczba wolnych slotów RAM": "brak danych",
      "Pojemność dysku": "1024 GB",
      "Typ dysku twardego": "SSD",
      "Prędkość obrotowa dysku HDD": "brak danych",
      "Rodzaj karty graficznej": "Grafika dedykowana",
      "Model karty graficznej": "NVIDIA GeForce RTX 3070",
      "Pamięć karty graficznej": "8 GB",
      "Pojemność akumulatora (Wh)": "80 Wh",
      "Pojemność akumulatora (mAh)": "brak danych",
      "Maksymalny czas pracy baterii": "4\t2 h",
      "Typ napędu": "brak",
      "Złącza": "HDMI\t inne\t minijack 3\t5 mm (audio)\t RJ-45\t USB 3.1 typ A\t USB 3.1 typ C",
      "Komunikacja": "Bluetooth\t LAN 10/100/1000 Mbps\t Wi-Fi",
      "Multimedia": "głośniki\t kamera\t mikrofon",
      "Sterowanie": "klawiatura\t klawiatura numeryczna\t klawiatura podświetlana\t touchpad",
      "Kolor": "szary",
      "Materiał": "metal",
      "Szerokość produktu": "35\t6 cm",
      "Wysokość produktu": "2\t1 cm",
      "Głębokość produktu": "26\t04 cm",
      "Waga produktu": "2\t45 kg",
      "Zdjęcie": "https://a.allegroimg.com/original/119fbd/5b894d0e44aaac0a48fad9de5cac"
    }
  ]

  export default mockData;